### PR TITLE
chore: replace validator package 'joi' to 'yup' to get better type safety

### PR DESCRIPTION
**Pull request by Dilven**
It seems worth using a package that will give us a better type-safe. Let me know what you think about it

image

After that, It would be nice if yupValidator, could give us the inferred type to handlers based on the schema

### CODE REVIEW

**Comment by sethii** [comment]
@Dilven to be honest I'm not convinced if we should switch from Joi to yup. The types are a huge advantage, yet Joi has many more built-in validators, allowing us to create more accurate schemas. 

Obviously, we can code the same with yup, but then we still have to code those. Instead of yup I'd rather see the option to get types from Joi - back then there was a feature to extract types based on validations and as far as I see this topic was raised again just recently.

**Comment by sethii** [comment]
On the other hand, if we were to change a validation library to get the full benefits of TS, we should probably switch to Zod instead as it is the only TS first parsing library used by tRPC.

**Comment by Dilven** [comment]
Thanks for review!

my first idea was to extract types from `joi` but it requires an additional package from us and `joi` doesn't look like type-safe package by design. And then (what is funny) I thought about `zod` but compare it to the `joi` and `yup` is less popular. But of course, if you use `tRPC` and there `zod` is used it is also a good idea. 

I didn't know that you use a lot built-in validators from `joi` but maybe it's not necessary for all projects?

**Comment by sethii** [comment]
@Dilven and so we finally migrated to Zod - https://github.com/TheSoftwareHouse/serverless-boilerplate/pull/23 :)

**Pull request closed without merging**
